

artifact_root: artifacts 

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/hotel_reservations.parquet
  val_status: artifacts/data_validation/validation_status.json
  validated_data: artifacts/data_validation/hotel_val_data.parquet
  all_schema:
    hotel: object
    is_canceled: int64  
    lead_time                    : int64  
    meal                         : object 
    market_segment               : object 
    distribution_channel         : object 
    reserved_room_type           : object 
    assigned_room_type           : object 
    booking_changes              : int64  
    deposit_type                 : object 
    customer_type                : object 
    adr                          : float64
    required_car_parking_spaces  : int64  
    total_of_special_requests    : int64  
    reservation_status           : object 
    total_booking_days           : int64  
    total_guests                 : float64
